name: Build and test lab-cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test cicd-lab
    steps:
      - uses: actions/checkout@v4

      # Install our NPM dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./lab-cicd

      # Run our unit tests
      - name: Run unit tests
        run: npm run test
        working-directory: ./lab-cicd